### PR TITLE
upgrade tsuru module (fix login on WSL)

### LINKED ISSUE #203: tsuru login (with oAuth) fails on Windows (under WSL2)
`tsuru login` fails under WSL2. 
It tries to open `http://127.0.0.1:PORT?xxxxxx` and it fails. It works if we open `http://localhost:PORT?xxxxxx` instead.

### PR DESCRIPTION
**Pull request by tcarreira**
upgrade tsuru module (support login on windows under WSL)

it required upgrading go version, and removing some deprecated code (dockermachine)

closes #203

### CODE REVIEW

File: tsuru/main.go [hunk 1]
```diff
@@ -228,21 +222,14 @@ func recoverCmdPanicExitError() {
...
-			log.Fatalf("Error running driver: %s", err)
-		}
-	} else {
-		defer config.SaveChangesWithTimeout()
+	checkVerResult := selfupdater.CheckLatestVersionBackground(version)
+	defer selfupdater.VerifyLatestVersion(checkVerResult)
 
-		checkVerResult := selfupdater.CheckLatestVersionBackground(version)
-		defer selfupdater.VerifyLatestVersion(checkVerResult)
+	localbinary.CurrentBinaryIsDockerMachine = true
```
Comment (wpjunior) [inline tsuru/main.go:230]: @tcarreira localbinary is not necessary

Comment (tcarreira) [reply tsuru/main.go:230]: I'm not sure what it does, I did not change it. 
You think I should I remove that line?

Comment (tcarreira) [reply tsuru/main.go]: removed ;)
